apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  project: default
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io
    targetRevision: 1.17.5
    helm:
      releaseName: rook-ceph
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
